from dateutil.tz import tzlocal
import datetime
from datetime import date

multiple_transactions_dict = [[{'account_id': 'JrJZmPgzGACD3naN3DP5sP9W4d8mdxCQegPGk',
'account_owner': None,
'amount': 896.65,
'authorized_date': datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Transfer', 'Debit'],
'category_id': '21006000',
'check_number': None,
'date': datetime.date(2022, 12, 17),
'datetime': None,
'iso_currency_code': 'USD',
'location': {'address': None,
          'city': None,
          'country': None,
          'lat': None,
          'lon': None,
          'postal_code': None,
          'region': None,
          'store_number': None},
'merchant_name': None,
'name': 'DEBIT CRD AUTOPAY 98712 000000000028791 KIUYPWRSGTKF UXYOTLLKJHA C',
'payment_channel': 'in store',
'payment_meta': {'by_order_of': None,
              'payee': None,
              'payer': None,
              'payment_method': None,
              'payment_processor': None,
              'ppd_id': None,
              'reason': None,
              'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': 'PaJgwMn4y9fbPzjdPbl5hg9zN8kg1pSXyWRn6',
'transaction_type': 'special',
'unofficial_currency_code': None}, {'account_id': 'PaJgwMn4y9fbPzjdPbl5hg9qkab8awCXyWRnv',
'account_owner': None,
'amount': 398.34,
'authorized_date': datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Transfer', 'Debit'],
'category_id': '21006000',
'check_number': None,
'date': datetime.date(2022, 12, 17),
'datetime': None,
'iso_currency_code': 'USD',
'location': {'address': None,
          'city': None,
          'country': None,
          'lat': None,
          'lon': None,
          'postal_code': None,
          'region': None,
          'store_number': None},
'merchant_name': None,
'name': 'DEBIT CRD AUTOPAY 98712 000000000098712 WRSGTKIUYPKF KJHAUXYOTLL A',
'payment_channel': 'in store',
'payment_meta': {'by_order_of': None,
              'payee': None,
              'payer': None,
              'payment_method': None,
              'payment_processor': None,
              'ppd_id': None,
              'reason': None,
              'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': '4e1XPQq43Bs5L4m6L5pEFGgjMA5GQvUlRAPKp',
'transaction_type': 'special',
'unofficial_currency_code': None}, {'account_id': 'JrJZmPgzGACD3naN3DP5sP9W4d8mdxCQegPGk',
'account_owner': None,
'amount': 1708.12,
'authorized_date': datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Food and Drink', 'Restaurants'],
'category_id': '13005000',
'check_number': None,
'date': datetime.date(2022, 12, 16),
'datetime': None,
'iso_currency_code': 'USD',
'location': {'address': None,
          'city': None,
          'country': None,
          'lat': None,
          'lon': None,
          'postal_code': None,
          'region': None,
          'store_number': None},
'merchant_name': None,
'name': 'CREDIT CRD AUTOPAY 29812 000000000098123 CRGKFKKSPABG UXZYOTAYLDA D',
'payment_channel': 'in store',
'payment_meta': {'by_order_of': None,
              'payee': None,
              'payer': None,
              'payment_method': None,
              'payment_processor': None,
              'ppd_id': None,
              'reason': None,
              'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': 'NxJp9Qkdemcw4X7L4wW5cwqryvjwepTXA5wzp',
'transaction_type': 'place',
'unofficial_currency_code': None}, {'account_id': 'PaJgwMn4y9fbPzjdPbl5hg9qkab8awCXyWRnv',
'account_owner': None,
'amount': 1109.01,
'authorized_date': datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Transfer', 'Debit'],
'category_id': '21006000',
'check_number': None,
'date': datetime.date(2022, 12, 16),
'datetime': None,
'iso_currency_code': 'USD',
'location': {'address': None,
          'city': None,
          'country': None,
          'lat': None,
          'lon': None,
          'postal_code': None,
          'region': None,
          'store_number': None},
'merchant_name': None,
'name': 'CREDIT CRD AUTOPAY 29812 000000000098123 KABCRGKSPKFG YOTALDUXZYA B',
'payment_channel': 'in store',
'payment_meta': {'by_order_of': None,
              'payee': None,
              'payer': None,
              'payment_method': None,
              'payment_processor': None,
              'ppd_id': None,
              'reason': None,
              'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': 'aWQwlaxAE4tKn1bEnKAvimBLNpMm7DtkKQMvK',
'transaction_type': 'special',
'unofficial_currency_code': None}], [{'account_id': 'bMXdQVkDRXHABLR5bZnycpXjq3qnP9uomZJK3',
'account_owner': None,
'amount': 896.65,
'authorized_date': datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Payment', 'Credit Card'],
'category_id': '16001000',
'check_number': None,
'date': datetime.date(2022, 12, 17),
'datetime': None,
'iso_currency_code': 'USD',
'location': {'address': None,
          'city': None,
          'country': None,
          'lat': None,
          'lon': None,
          'postal_code': None,
          'region': None,
          'store_number': None},
'merchant_name': None,
'name': 'DEBIT CRD AUTOPAY 98712 000000000028791 KIUYPWRSGTKF UXYOTLLKJHA C',
'payment_channel': 'other',
'payment_meta': {'by_order_of': None,
              'payee': None,
              'payer': None,
              'payment_method': None,
              'payment_processor': None,
              'ppd_id': None,
              'reason': None,
              'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': 'V3LRGAPZzLfeDz1MxgGRfeLXr7BlbQfqdvgJy',
'transaction_type': 'special',
'unofficial_currency_code': None}, {'account_id': 'nrDL1VlR6DI4zMo5AXgdFwlRaJamZ7U3AWXVK',
'account_owner': None,
'amount': 398.34,
'authorized_date': datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Payment', 'Credit Card'],
'category_id': '16001000',
'check_number': None,
'date': datetime.date(2022, 12, 17),
'datetime': None,
'iso_currency_code': 'USD',
'location': {'address': None,
          'city': None,
          'country': None,
          'lat': None,
          'lon': None,
          'postal_code': None,
          'region': None,
          'store_number': None},
'merchant_name': None,
'name': 'DEBIT CRD AUTOPAY 98712 000000000098712 WRSGTKIUYPKF KJHAUXYOTLL A',
'payment_channel': 'other',
'payment_meta': {'by_order_of': None,
              'payee': None,
              'payer': None,
              'payment_method': None,
              'payment_processor': None,
              'ppd_id': None,
              'reason': None,
              'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': 'XdGXEn7b3GsZM5zLn8NpCzQ6apBZN8C1ErKRv',
'transaction_type': 'special',
'unofficial_currency_code': None}]]
