from dateutil.tz import tzlocal
import datetime
from datetime import date
single_transaction_dict = [[{'account_id': 'kK3EeGbokrHnb1GWao1wc5rbep6npEIJQLxLa',
'account_owner': None,
'amount': 500.0,
'authorized_date':datetime.date(2022, 12, 16),
'authorized_datetime': None,
'category': ['Travel', 'Airlines and Aviation Services'],
'category_id': '22001000',
'check_number': None,
'date': datetime.date(2022, 12, 16),
'datetime': None,
'iso_currency_code': 'GBP',
'location': {'address': None,
      'city': None,
      'country': None,
      'lat': None,
      'lon': None,
      'postal_code': None,
      'region': None,
      'store_number': None},
'merchant_name': 'United Airlines',
'name': 'United Airlines',
'payment_channel': 'in store',
'payment_meta': {'by_order_of': None,
          'payee': None,
          'payer': None,
          'payment_method': None,
          'payment_processor': None,
          'ppd_id': None,
          'reason': None,
          'reference_number': None},
'pending': False,
'pending_transaction_id': None,
'personal_finance_category': None,
'transaction_code': None,
'transaction_id': 'M3vq1AwVoBIGj5kv8X5oFlVw6pmLAziLGk1nk',
'transaction_type': 'special',
'unofficial_currency_code': None}]]
