# Generated by Django 4.1.5 on 2023-01-28 14:32

import assetManager.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', assetManager.models.UserManager()),
            ],
        ),
    ]
