# Generated by Django 4.1.5 on 2023-02-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='access_token',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
