# Generated by Django 4.1.5 on 2023-01-30 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=520, validators=[django.core.validators.RegexValidator(message='Password must contain at least one uppercase character, one lowercase character and a number', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).*$')]),
        ),
    ]
