# Generated by Django 4.1.5 on 2023-02-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0002_alter_accounttype_access_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('account_type_id', 'user')},
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='access_token',
            field=models.CharField(max_length=250),
        ),
    ]
