# Generated by Django 4.1.5 on 2023-02-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0003_alter_accounttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('account_type_id', 'access_token', 'user')},
        ),
    ]
