# Generated by Django 4.1.5 on 2023-02-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0004_accounttype_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='account_firm_name',
            new_name='account_institution_name',
        ),
    ]
