# Generated by Django 4.1.5 on 2023-03-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0005_alter_accounttype_account_asset_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('access_token', 'user')},
        ),
    ]
