# Generated by Django 4.1.5 on 2023-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0005_rename_account_firm_name_accounts_account_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_asset_type',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card'), ('STOCK', 'Brokerage or Investement Account'), ('CRYPTO', 'Crypto Wallet')], max_length=35),
        ),
    ]
