# Generated by Django 4.1.5 on 2023-03-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0006_alter_accounttype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('access_token', 'user', 'account_asset_type')},
        ),
    ]
